### login api
POST http://127.0.0.1:8000/api/login
Content-Type: application/json
{
  "email": "meyorpop@gmail.com",
  "password": "1234password"
}

### logout api
POST http://127.0.0.1:8000/api/logout


### Get videos api
GET http://127.0.0.1:8000/api/videos


### Get video by id api
GET http://127.0.0.1:8000/api/videos/1

### Get video by id api
